version: 2.1

jobs:
  rspec:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
    docker:
      - image: ruby:<< parameters.ruby-version >>
      - image: cimg/postgres:11.16
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec appraisal << parameters.gemfile >> bundle install
      - run: bundle exec appraisal << parameters.gemfile >> rspec

workflows:
  test:
    jobs:
      - rspec:
          matrix:
            parameters:
              ruby-version:
                - '2.7'
                - '3.0'
                - '3.1'
              gemfile:
                - rails-6.0
                - rails-6.1
                - rails-7.0
                - rails-main
            exclude:
              - ruby-version: '3.0'
                gemfile: rails-6.0
              - ruby-version: '3.1'
                gemfile: rails-6.0
