version: 2.1

executors:
  ruby_2_5:
    docker:
      - image: ruby:2.5.3
      - image: circleci/postgres:11-alpine

jobs:
  run_rspec:
    executor: ruby_2_5
    parameters:
      gemfile:
        type: string
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec appraisal << parameters.gemfile >> bundle install
      - run: bundle exec appraisal << parameters.gemfile >> rspec

workflows:
  version: 2

  test:
    jobs: &jobs
      - run_rspec:
          gemfile: rails-5.2
      - run_rspec:
          gemfile: rails-6.0
      - run_rspec:
          gemfile: rails-master

  daily_test:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs: *jobs
