name: CodeSpell
on:
  - pull_request
env:
  NPM_CONFIG_IGNORE_SCRIPTS: 'true'
  NPM_CONFIG_BEFORE: ''
  PNPM_CONFIG_MINIMUM_RELEASE_AGE: '1440' # 1 day
jobs:
  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    steps:
      - name: Set NPM_CONFIG_BEFORE
        run: |
          echo "NPM_CONFIG_BEFORE=$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: CodeSpell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
