# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  push:
    branches:
      - master
  pull_request:

env:
  NPM_CONFIG_IGNORE_SCRIPTS: 'true'
  NPM_CONFIG_BEFORE: ''
  PNPM_CONFIG_MINIMUM_RELEASE_AGE: '1440' # 1 day

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Set NPM_CONFIG_BEFORE
        run: |
          echo "NPM_CONFIG_BEFORE=$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - run: bundle exec rubocop
