# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - run: bundle exec rubocop
